image: node:latest

stages:
  - build
  - deploy

before_script:
    - npm install -g @angular/cli@
    - npm ci


build_development:
  stage: build
  only:
    - development
  script:
    - ng build
  artifacts:
    paths:
      - dist/
  cache:
    paths:
      - node_modules/

build_master:
    stage: build
    only:
        - master
        - aws_deployment # TODO: REMOVE
    script:
        - ng build --prod
    artifacts:
        paths:
            - dist/


deploy_master:
    stage: deploy
    only:
        - master
        - aws_deployment # TODO: REMOVE
    image: python:latest
    before_script:
        - pip install awscli
    script:
        - aws s3 sync ./dist/climate-site s3://climate-site/ --acl=public-read --delete
