image: node:latest

stages:
  - build
  - test
  - deploy

before_script:
  - npm install -g @angular/cli@
  - npm ci

test:
  image: trion/ng-cli-karma:latest
  allow_failure: false
  script:
  - ng test --progress false --watch false
  tags:
  - docker

build_development:
  stage: build
  only:
    - development
  script:
    - ng build
  artifacts:
    paths:
      - dist/
  cache:
    paths:
      - node_modules/

build_master:
    stage: build
    only:
        - master
    script:
        - ng build --prod
    artifacts:
        paths:
            - dist/


deploy_master:
    stage: deploy
    only:
        - master
    image: python:latest
    before_script:
        - pip install awscli
    script:
        - aws s3 sync ./dist/climate-site s3://climate-site/ --acl=public-read --delete --debug
